apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-04-04T09:35:54Z
  labels:
    kops.k8s.io/cluster: company.org
  name: gpu-nodes
spec:
  hooks:
  - before:
    - docker.service
    manifest: |
      Type=oneshot
      ExecStart=/bin/bash -c '/usr/bin/curl -L -S -f https://raw.githubusercontent.com/brunsgaard/kops-nvidia-docker-installer/master/entrypoint.sh | /bin/bash'
    name: nvidia-docker-install.service
  image: kope.io/k8s-1.8-debian-stretch-amd64-hvm-ebs-2018-02-08
  machineType: p2.xlarge
  maxSize: 4
  minSize: 0
  nodeLabels:
    kops.k8s.io/instancegroup: gpu-nodes
  role: Node
  subnets:
  - eu-central-1a
  - eu-central-1b
  taints:
  - nvidia.com/gpu=:NoSchedule
